### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ashfame** [apertureless/wipfred#1]
Hey Jakub,

This looked sweet, so when I tried installing it, I got this error.
This is a fresh Alfred 3 installation, a minute ago.

Log:
```
5284 silly postinstall wipfred@1.0.0
5285 info lifecycle wipfred@1.0.0~postinstall: wipfred@1.0.0
5286 verbose lifecycle wipfred@1.0.0~postinstall: unsafe-perm in lifecycle true
5287 verbose lifecycle wipfred@1.0.0~postinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/wipfred/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/Cellar/php/7.2.5/bin:/usr/local/opt/curl/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/opt/go/libexec/bin:/Users/ashfame/.go/bin
5288 verbose lifecycle wipfred@1.0.0~postinstall: CWD: /usr/local/lib/node_modules/wipfred
5289 silly lifecycle wipfred@1.0.0~postinstall: Args: [ '-c', 'alfy-init' ]
5290 silly lifecycle wipfred@1.0.0~postinstall: Returned: code: 1  signal: null
5291 info lifecycle wipfred@1.0.0~postinstall: Failed to exec postinstall script
5292 verbose unlock done using /Users/ashfame/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
5293 verbose stack Error: wipfred@1.0.0 postinstall: `alfy-init`
5293 verbose stack Exit status 1
5293 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
5293 verbose stack     at EventEmitter.emit (events.js:160:13)
5293 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
5293 verbose stack     at ChildProcess.emit (events.js:160:13)
5293 verbose stack     at maybeClose (internal/child_process.js:943:16)
5293 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
5294 verbose pkgid wipfred@1.0.0
5295 verbose cwd /Users/ashfame
5296 verbose Darwin 17.5.0
5297 verbose argv "/usr/local/Cellar/node/9.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "wipfred"
5298 verbose node v9.5.0
5299 verbose npm  v5.6.0
5300 error code ELIFECYCLE
5301 error errno 1
5302 error wipfred@1.0.0 postinstall: `alfy-init`
5302 error Exit status 1
5303 error Failed at the wipfred@1.0.0 postinstall script.
5303 error This is probably not a problem with npm. There is likely additional logging output above.
5304 verbose exit [ 1, true ]```

**Comment by ashfame** [comment]
Perhaps cuz I don't have Powerpack?

**Comment by apertureless** [comment]
Hey @ashfame 
I guess you have node 4+ ?

This certainly could be related to the missing Powerpack. As far as I remember the powerpack is required for all custom workflows. However I would expect that the install will finish and you just can't use it. But maybe the powerpack enables some features that [alfy](https://github.com/sindresorhus/alfy) is using to install the workflow. 

I will try to check on this. 🔍 

I also added the workflow file in the release section https://github.com/apertureless/wipfred/releases/tag/v1.0.0

So you could try to download the `wipfred.alfredworkflow` file and try to double click it. Normally it should install it. But like said before, the powerpack is generally required for workflows.

**Comment by ashfame** [comment]
```
ashfame@ ~ () $ node -v
v9.5.0
ashfame@ ~ () $ npm -v
5.6.0
```

Yeah directly opening the workflow file prompts me that powerpack is required. I will revisit this at a later date. Very cool project indeed!

**Comment by apertureless** [comment]
✌️
