### ISSUE TITLE
Preferences not found error.

### ISSUE THREAD

**Issue by mulholo** [apertureless/wipfred#4]
Seem to be getting an error when using npm to install. Have no memory of moving any alfred preferences around.

```
{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/jamesmulholland/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/wipfred/node_modules/resolve-alfred-prefs/index.js:15:10)
    at <anonymous>


    at Promise.all.then.arr (/usr/local/lib/node_modules/wipfred/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Error: Alfred preferences not found at location /Users/jamesmulholland/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/wipfred/node_modules/resolve-alfred-prefs/index.js:15:10)\n    at <anonymous>\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false }
```

**Comment by apertureless** [comment]
- Do you have Alfred + Powerpack?
- Can you confirm that the location exists?
- Maybe this helps you https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md 

Someone on twitter got the same error: https://twitter.com/FZTSH/status/993897050126409728

**Comment by apertureless** [comment]
Hey @mulholio any updates on this?

**Comment by apertureless** [comment]
closed due to inactivity
